### ISSUE TITLE
Support for Bean Converter

### ISSUE THREAD

**Issue by lofei117** [andrasferenczi/dart-data-plugin#20]
Is there any plan for supporting "Bean Converter"? Like convert "PersonDo" to "PersonVo".  
Really need that, thanks very much. 😁

**Comment by andrasferenczi** [comment]
I don't understand what that is. If I understand correctly though that you want to convert between two classes that have the same fields, then you can just convert to map and then parse the other from map

**Comment by lofei117** [comment]
> I don't understand what that is. If I understand correctly though that you want to convert between two classes that have the same fields, then you can just convert to map and then parse the other from map


Yeah, in most cases the two class have the same fields, but sometimes not. 

If I use map, fields should be `dynamic` (`Map<String, dynamic>`),  when transform from `Map` to `Class`, object type is not type-safe that I should use `as` to cast it. 
When use object-to-object convert, I can see the field type at compile time, and the compiler will throw error when the types are not match.

**Comment by andrasferenczi** [comment]
I tried to create a similar thing when I was implementing a `spread operator` feature (remove since), as seen in this [.gif](https://github.com/andrasferenczi/dart-data-plugin/blob/master/img/dart-spread-usage.gif). The idea was that if a function or constructor call expects arguments by specific name, the plugin tries to match the named parameters by the names currently available.

So lets say you in the current scope you have `name` available and a `Person` class that has `name` and `age` and you would want to call a function that expects `name` and `age` as the argument, then it would fill in automatically using these variables (`name` taking higher priority in this case).

The thing you are describing is quite similar I think.

I didn't get any feedback on this `spread operator` feature if anyone used it at all, so I stopped it entirely (it had compatibility issues with newer plugin) and was a bit hacky.

**Comment by lofei117** [comment]
Well, It seems that's what I need.  
I will checkout the commit, build the plugin and take an experience, I will give you my feedback after using it in a few weeks. 

Thanks a lot. 👍 😁

**Comment by lofei117** [comment]
Well, time flies. I have been writing Dart/Flutter for two years. In the past two years, the top two features which I used most are "Named Argument Constructor" and "Copy". 
"Bean Converter" is not the key-feature during product development.  
Sorry for making noise.
